# Logo
logo: # Empty this to unset logo

# Header
menu:
  Archives: archives
  Categories: categories
  Tags: tags
  #About: about

# Content
excerpt_link: Read More
fancybox: true

# Profile
profile: true # whether to show profile bar
gravatar: false # whether to use gravatar with the email
showlogo: false # whether to show the logo in the header

# Sidebar
sidebar: right # set to false if you don't want a sidebar
widgets:
- recent_posts
- category
- tag
- archive
thumbnail: false

# Contacts
contacts:
  github: https://github.com/ivanjonas
  twitter: https://twitter.com/iv_njonas
  #rss: atom.xml

# Links
#links:
#  Hexo: http://hexo.io

# CDN
cdn: google #If your site loads slowly change it to "google" , because "useso" is slow out of China

# Miscellaneous
google_site_verification: Pd8UOkM5hC_fSi2jhMJ5STXnDPX4Slkhn5NxM1jfPc0
google_analytics: UA-68773216-1
favicon: favicon.png
twitter: https://twitter.com/_jnblog
google_plus:
fb_admins:
fb_app_id:
